using AccountOS.Domain.Common;
using AccountOS.Domain.Enums;

namespace AccountOS.Domain.Entities;

/// <summary>
/// Yevmiye kaydı (Journal Entry)
/// </summary>
public class JournalEntry : TenantEntity
{
    /// <summary>Kayıt numarası</summary>
    public string EntryNumber { get; set; } = string.Empty;
    
    /// <summary>Kayıt tarihi</summary>
    public DateTime EntryDate { get; set; }
    
    /// <summary>Kayıt tipi</summary>
    public JournalEntryType EntryType { get; set; }
    
    /// <summary>Bağlı olduğu entity tipi (Invoice, Payment, etc.)</summary>
    public string? ReferenceType { get; set; }
    
    /// <summary>Bağlı olduğu entity ID</summary>
    public Guid? ReferenceId { get; set; }
    
    /// <summary>Referans numarası (fatura no, ödeme no, etc.)</summary>
    public string? ReferenceNumber { get; set; }
    
    /// <summary>Açıklama</summary>
    public string Description { get; set; } = string.Empty;
    
    /// <summary>Para birimi</summary>
    public string Currency { get; set; } = "TRY";
    
    /// <summary>Toplam borç</summary>
    public decimal TotalDebit { get; set; }
    
    /// <summary>Toplam alacak</summary>
    public decimal TotalCredit { get; set; }
    
    /// <summary>Durum</summary>
    public JournalEntryStatus Status { get; set; }
    
    /// <summary>Onaylayan kullanıcı ID</summary>
    public Guid? ApprovedBy { get; set; }
    
    /// <summary>Onay tarihi</summary>
    public DateTime? ApprovedAt { get; set; }
    
    /// <summary>Otomatik oluşturuldu mu?</summary>
    public bool IsAutoGenerated { get; set; }
    
    /// <summary>Dönem (YYYY-MM)</summary>
    public string Period { get; set; } = string.Empty;
    
    // Navigation Properties
    public ICollection<JournalEntryLine> Lines { get; set; } = new List<JournalEntryLine>();
}

