using AccountOS.Domain.Enums;

namespace AccountOS.Application.Accounting.Common;

public record JournalEntryDto
{
    public Guid Id { get; init; }
    public string EntryNumber { get; init; } = string.Empty;
    public DateTime EntryDate { get; init; }
    public JournalEntryType EntryType { get; init; }
    public string EntryTypeName { get; init; } = string.Empty;
    public string? ReferenceType { get; init; }
    public Guid? ReferenceId { get; init; }
    public string? ReferenceNumber { get; init; }
    public string Description { get; init; } = string.Empty;
    public string Currency { get; init; } = string.Empty;
    public decimal TotalDebit { get; init; }
    public decimal TotalCredit { get; init; }
    public JournalEntryStatus Status { get; init; }
    public string StatusName { get; init; } = string.Empty;
    public bool IsAutoGenerated { get; init; }
    public string Period { get; init; } = string.Empty;
    public List<JournalEntryLineDto> Lines { get; init; } = new();
}

public record JournalEntryLineDto
{
    public Guid Id { get; init; }
    public Guid AccountId { get; init; }
    public string AccountCode { get; init; } = string.Empty;
    public string AccountName { get; init; } = string.Empty;
    public int LineNumber { get; init; }
    public string? Description { get; init; }
    public decimal DebitAmount { get; init; }
    public decimal CreditAmount { get; init; }
    public string Currency { get; init; } = string.Empty;
}

