using AccountOS.Application.Accounting.Common;
using AccountOS.Application.Common;
using AccountOS.Application.Common.Interfaces;
using AccountOS.Domain.Enums;
using MediatR;
using Microsoft.EntityFrameworkCore;

namespace AccountOS.Application.Accounting.Commands.CreateJournalEntry;

public class CreateJournalEntryCommandHandler 
    : IRequestHandler<CreateJournalEntryCommand, Result<JournalEntryDto>>
{
    private readonly IApplicationDbContext _context;
    private readonly IJournalEntryService _journalEntryService;

    public CreateJournalEntryCommandHandler(
        IApplicationDbContext context,
        IJournalEntryService journalEntryService)
    {
        _context = context;
        _journalEntryService = journalEntryService;
    }

    public async Task<Result<JournalEntryDto>> Handle(
        CreateJournalEntryCommand request, 
        CancellationToken cancellationToken)
    {
        // Validate: Total Debit = Total Credit
        var totalDebit = request.Lines.Sum(l => l.DebitAmount);
        var totalCredit = request.Lines.Sum(l => l.CreditAmount);

        if (totalDebit != totalCredit)
            return Result<JournalEntryDto>.Fail("Toplam borç ve alacak eşit olmalıdır");

        if (request.Lines.Count < 2)
            return Result<JournalEntryDto>.Fail("En az 2 satır gereklidir");

        // Create journal entry
        var lines = request.Lines.Select(l => (
            AccountId: l.AccountId,
            Debit: l.DebitAmount,
            Credit: l.CreditAmount,
            Description: l.Description
        )).ToList();

        var journalEntryId = await _journalEntryService.CreateManualJournalEntryAsync(
            request.EntryDate,
            request.Description,
            lines,
            cancellationToken);

        // Get created journal entry
        var journalEntry = await _context.JournalEntries
            .Include(j => j.Lines)
            .ThenInclude(l => l.Account)
            .Where(j => j.Id == journalEntryId)
            .FirstOrDefaultAsync(cancellationToken);

        if (journalEntry == null)
            return Result<JournalEntryDto>.Fail("Yevmiye kaydı oluşturulamadı");

        var dto = new JournalEntryDto
        {
            Id = journalEntry.Id,
            EntryNumber = journalEntry.EntryNumber,
            EntryDate = journalEntry.EntryDate,
            EntryType = journalEntry.EntryType,
            EntryTypeName = GetEntryTypeName(journalEntry.EntryType),
            ReferenceType = journalEntry.ReferenceType,
            ReferenceId = journalEntry.ReferenceId,
            ReferenceNumber = journalEntry.ReferenceNumber,
            Description = journalEntry.Description,
            Currency = journalEntry.Currency,
            TotalDebit = journalEntry.TotalDebit,
            TotalCredit = journalEntry.TotalCredit,
            Status = journalEntry.Status,
            StatusName = GetStatusName(journalEntry.Status),
            IsAutoGenerated = journalEntry.IsAutoGenerated,
            Period = journalEntry.Period,
            Lines = journalEntry.Lines.Select(l => new JournalEntryLineDto
            {
                Id = l.Id,
                AccountId = l.AccountId,
                AccountCode = l.Account.AccountCode,
                AccountName = l.Account.AccountName,
                LineNumber = l.LineNumber,
                Description = l.Description,
                DebitAmount = l.DebitAmount,
                CreditAmount = l.CreditAmount,
                Currency = l.Currency
            }).ToList()
        };

        return Result<JournalEntryDto>.Ok(dto);
    }

    private static string GetEntryTypeName(JournalEntryType type)
    {
        return type switch
        {
            JournalEntryType.Standard => "Standart",
            JournalEntryType.Opening => "Açılış",
            JournalEntryType.Closing => "Kapanış",
            JournalEntryType.Adjustment => "Düzeltme",
            JournalEntryType.Reversal => "Ters Kayıt",
            JournalEntryType.Accrual => "Tahakkuk",
            _ => type.ToString()
        };
    }

    private static string GetStatusName(JournalEntryStatus status)
    {
        return status switch
        {
            JournalEntryStatus.Draft => "Taslak",
            JournalEntryStatus.PendingApproval => "Onay Bekliyor",
            JournalEntryStatus.Approved => "Onaylandı",
            JournalEntryStatus.Posted => "Deftere İşlendi",
            JournalEntryStatus.Cancelled => "İptal Edildi",
            _ => status.ToString()
        };
    }
}

