using AccountOS.Application.Common;
using AccountOS.Application.Common.Interfaces;
using AccountOS.Domain.Entities;
using AccountOS.Domain.Enums;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace AccountOS.Infrastructure.Services;

/// <summary>
/// Yevmiye kaydı servisi implementation
/// </summary>
public class JournalEntryService : IJournalEntryService
{
    private readonly IApplicationDbContext _context;
    private readonly ICurrentUserService _currentUser;
    private readonly IDocumentNumberingService _numberingService;
    private readonly ILogger<JournalEntryService> _logger;

    public JournalEntryService(
        IApplicationDbContext context,
        ICurrentUserService currentUser,
        IDocumentNumberingService numberingService,
        ILogger<JournalEntryService> logger)
    {
        _context = context;
        _currentUser = currentUser;
        _numberingService = numberingService;
        _logger = logger;
    }

    public async Task CreateInvoiceJournalEntryAsync(
        Guid invoiceId,
        CancellationToken cancellationToken = default)
    {
        try
        {
            var invoice = await _context.Invoices
                .Include(i => i.Items)
                .Where(i => i.Id == invoiceId)
                .FirstOrDefaultAsync(cancellationToken);

            if (invoice == null)
            {
                _logger.LogWarning("Invoice {InvoiceId} not found", invoiceId);
                return;
            }

            // Get accounts
            var receivableAccount = await GetSystemAccountAsync("120", cancellationToken); // Alıcılar
            var revenueAccount = await GetSystemAccountAsync("600", cancellationToken); // Satış Gelirleri
            var vatPayableAccount = await GetSystemAccountAsync("391", cancellationToken); // Hesaplanan KDV

            if (receivableAccount == null || revenueAccount == null || vatPayableAccount == null)
            {
                _logger.LogError("System accounts not found for invoice journal entry");
                return;
            }

            // Create journal entry
            var entryNumber = await _numberingService.GenerateNumberAsync("JE", cancellationToken: cancellationToken);
            var period = invoice.InvoiceDate.ToString("yyyy-MM");

            var journalEntry = new JournalEntry
            {
                Id = Guid.NewGuid(),
                CompanyId = invoice.CompanyId,
                EntryNumber = entryNumber,
                EntryDate = invoice.InvoiceDate,
                EntryType = JournalEntryType.Standard,
                ReferenceType = "Invoice",
                ReferenceId = invoice.Id,
                ReferenceNumber = invoice.InvoiceNumber,
                Description = $"Fatura: {invoice.InvoiceNumber}",
                Currency = invoice.Currency,
                TotalDebit = invoice.GrandTotal,
                TotalCredit = invoice.GrandTotal,
                Status = JournalEntryStatus.Posted,
                IsAutoGenerated = true,
                Period = period,
                CreatedAt = DateTime.UtcNow,
                CreatedBy = _currentUser.UserId ?? Guid.Empty
            };

            // Line 1: Debit - Accounts Receivable (Grand Total)
            journalEntry.Lines.Add(new JournalEntryLine
            {
                Id = Guid.NewGuid(),
                JournalEntryId = journalEntry.Id,
                AccountId = receivableAccount.Id,
                LineNumber = 1,
                Description = $"Alacak - Fatura {invoice.InvoiceNumber}",
                DebitAmount = invoice.GrandTotal,
                CreditAmount = 0,
                Currency = invoice.Currency,
                CreatedAt = DateTime.UtcNow,
                CreatedBy = _currentUser.UserId ?? Guid.Empty
            });

            // Line 2: Credit - Revenue (Subtotal)
            journalEntry.Lines.Add(new JournalEntryLine
            {
                Id = Guid.NewGuid(),
                JournalEntryId = journalEntry.Id,
                AccountId = revenueAccount.Id,
                LineNumber = 2,
                Description = "Satış Geliri",
                DebitAmount = 0,
                CreditAmount = invoice.SubTotal,
                Currency = invoice.Currency,
                CreatedAt = DateTime.UtcNow,
                CreatedBy = _currentUser.UserId ?? Guid.Empty
            });

            // Line 3: Credit - VAT Payable
            if (invoice.VatTotal > 0)
            {
                journalEntry.Lines.Add(new JournalEntryLine
                {
                    Id = Guid.NewGuid(),
                    JournalEntryId = journalEntry.Id,
                    AccountId = vatPayableAccount.Id,
                    LineNumber = 3,
                    Description = "Hesaplanan KDV",
                    DebitAmount = 0,
                    CreditAmount = invoice.VatTotal,
                    Currency = invoice.Currency,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = _currentUser.UserId ?? Guid.Empty
                });
            }

            _context.JournalEntries.Add(journalEntry);
            await _context.SaveChangesAsync(cancellationToken);

            _logger.LogInformation("Journal entry {EntryNumber} created for invoice {InvoiceNumber}", 
                entryNumber, invoice.InvoiceNumber);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error creating journal entry for invoice {InvoiceId}", invoiceId);
        }
    }

    public async Task CreatePaymentJournalEntryAsync(
        Guid paymentId,
        CancellationToken cancellationToken = default)
    {
        // TODO: Implement payment journal entry
        await Task.CompletedTask;
    }

    public async Task CreateExpenseJournalEntryAsync(
        Guid expenseId,
        CancellationToken cancellationToken = default)
    {
        // TODO: Implement expense journal entry
        await Task.CompletedTask;
    }

    public async Task<Guid> CreateManualJournalEntryAsync(
        DateTime entryDate,
        string description,
        List<(Guid AccountId, decimal Debit, decimal Credit, string? Description)> lines,
        CancellationToken cancellationToken = default)
    {
        if (_currentUser.CompanyId == null || _currentUser.UserId == null)
            throw new InvalidOperationException("User context not available");

        // Validate: Total Debit must equal Total Credit
        var totalDebit = lines.Sum(l => l.Debit);
        var totalCredit = lines.Sum(l => l.Credit);

        if (totalDebit != totalCredit)
            throw new InvalidOperationException($"Total debit ({totalDebit}) must equal total credit ({totalCredit})");

        var entryNumber = await _numberingService.GenerateNumberAsync("JE", cancellationToken: cancellationToken);
        var period = entryDate.ToString("yyyy-MM");

        var journalEntry = new JournalEntry
        {
            Id = Guid.NewGuid(),
            CompanyId = _currentUser.CompanyId.Value,
            EntryNumber = entryNumber,
            EntryDate = entryDate,
            EntryType = JournalEntryType.Standard,
            Description = description,
            Currency = "TRY",
            TotalDebit = totalDebit,
            TotalCredit = totalCredit,
            Status = JournalEntryStatus.Draft,
            IsAutoGenerated = false,
            Period = period,
            CreatedAt = DateTime.UtcNow,
            CreatedBy = _currentUser.UserId.Value
        };

        int lineNumber = 1;
        foreach (var line in lines)
        {
            journalEntry.Lines.Add(new JournalEntryLine
            {
                Id = Guid.NewGuid(),
                JournalEntryId = journalEntry.Id,
                AccountId = line.AccountId,
                LineNumber = lineNumber++,
                Description = line.Description,
                DebitAmount = line.Debit,
                CreditAmount = line.Credit,
                Currency = "TRY",
                CreatedAt = DateTime.UtcNow,
                CreatedBy = _currentUser.UserId.Value
            });
        }

        _context.JournalEntries.Add(journalEntry);
        await _context.SaveChangesAsync(cancellationToken);

        return journalEntry.Id;
    }

    public async Task ApproveJournalEntryAsync(
        Guid journalEntryId,
        CancellationToken cancellationToken = default)
    {
        if (_currentUser.UserId == null)
            throw new InvalidOperationException("User context not available");

        var journalEntry = await _context.JournalEntries
            .Where(j => j.Id == journalEntryId)
            .FirstOrDefaultAsync(cancellationToken);

        if (journalEntry == null)
            throw new InvalidOperationException("Journal entry not found");

        if (journalEntry.Status != JournalEntryStatus.Draft && journalEntry.Status != JournalEntryStatus.PendingApproval)
            throw new InvalidOperationException("Journal entry cannot be approved in current status");

        journalEntry.Status = JournalEntryStatus.Approved;
        journalEntry.ApprovedBy = _currentUser.UserId.Value;
        journalEntry.ApprovedAt = DateTime.UtcNow;
        journalEntry.UpdatedAt = DateTime.UtcNow;
        journalEntry.UpdatedBy = _currentUser.UserId.Value;

        await _context.SaveChangesAsync(cancellationToken);
    }

    public async Task PostJournalEntryAsync(
        Guid journalEntryId,
        CancellationToken cancellationToken = default)
    {
        if (_currentUser.UserId == null)
            throw new InvalidOperationException("User context not available");

        var journalEntry = await _context.JournalEntries
            .Where(j => j.Id == journalEntryId)
            .FirstOrDefaultAsync(cancellationToken);

        if (journalEntry == null)
            throw new InvalidOperationException("Journal entry not found");

        if (journalEntry.Status != JournalEntryStatus.Approved)
            throw new InvalidOperationException("Journal entry must be approved before posting");

        journalEntry.Status = JournalEntryStatus.Posted;
        journalEntry.UpdatedAt = DateTime.UtcNow;
        journalEntry.UpdatedBy = _currentUser.UserId.Value;

        await _context.SaveChangesAsync(cancellationToken);
    }

    // Helper Methods

    private async Task<ChartOfAccount?> GetSystemAccountAsync(
        string accountCode,
        CancellationToken cancellationToken)
    {
        if (_currentUser.CompanyId == null)
            return null;

        return await _context.ChartOfAccounts
            .Where(a => a.CompanyId == _currentUser.CompanyId.Value
                     && a.AccountCode == accountCode
                     && a.IsActive)
            .FirstOrDefaultAsync(cancellationToken);
    }
}

