using AccountOS.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace AccountOS.Infrastructure.Persistence.Configurations;

public class JournalEntryConfiguration : IEntityTypeConfiguration<JournalEntry>
{
    public void Configure(EntityTypeBuilder<JournalEntry> builder)
    {
        builder.ToTable("journal_entries");

        builder.HasKey(j => j.Id);

        builder.Property(j => j.CompanyId)
            .IsRequired()
            .HasColumnName("company_id");

        builder.Property(j => j.EntryNumber)
            .IsRequired()
            .HasMaxLength(50)
            .HasColumnName("entry_number");

        builder.Property(j => j.EntryDate)
            .IsRequired()
            .HasColumnName("entry_date");

        builder.Property(j => j.EntryType)
            .IsRequired()
            .HasConversion<int>()
            .HasColumnName("entry_type");

        builder.Property(j => j.ReferenceType)
            .HasMaxLength(100)
            .HasColumnName("reference_type");

        builder.Property(j => j.ReferenceId)
            .HasColumnName("reference_id");

        builder.Property(j => j.ReferenceNumber)
            .HasMaxLength(100)
            .HasColumnName("reference_number");

        builder.Property(j => j.Description)
            .IsRequired()
            .HasMaxLength(1000)
            .HasColumnName("description");

        builder.Property(j => j.Currency)
            .IsRequired()
            .HasMaxLength(3)
            .HasColumnName("currency");

        builder.Property(j => j.TotalDebit)
            .IsRequired()
            .HasColumnName("total_debit")
            .HasColumnType("decimal(18,2)");

        builder.Property(j => j.TotalCredit)
            .IsRequired()
            .HasColumnName("total_credit")
            .HasColumnType("decimal(18,2)");

        builder.Property(j => j.Status)
            .IsRequired()
            .HasConversion<int>()
            .HasColumnName("status");

        builder.Property(j => j.ApprovedBy)
            .HasColumnName("approved_by");

        builder.Property(j => j.ApprovedAt)
            .HasColumnName("approved_at");

        builder.Property(j => j.IsAutoGenerated)
            .IsRequired()
            .HasColumnName("is_auto_generated");

        builder.Property(j => j.Period)
            .IsRequired()
            .HasMaxLength(10)
            .HasColumnName("period");

        // Audit fields
        builder.Property(j => j.CreatedAt).HasColumnName("created_at");
        builder.Property(j => j.CreatedBy).HasColumnName("created_by");
        builder.Property(j => j.UpdatedAt).HasColumnName("updated_at");
        builder.Property(j => j.UpdatedBy).HasColumnName("updated_by");
        builder.Property(j => j.IsDeleted).HasColumnName("is_deleted");
        builder.Property(j => j.DeletedAt).HasColumnName("deleted_at");
        builder.Property(j => j.DeletedBy).HasColumnName("deleted_by");

        // Indexes
        builder.HasIndex(j => new { j.CompanyId, j.EntryNumber })
            .IsUnique()
            .HasDatabaseName("ix_journal_entries_company_number");

        builder.HasIndex(j => new { j.CompanyId, j.EntryDate, j.Status })
            .HasDatabaseName("ix_journal_entries_company_date_status");

        builder.HasIndex(j => new { j.ReferenceType, j.ReferenceId })
            .HasDatabaseName("ix_journal_entries_reference");

        builder.HasIndex(j => new { j.CompanyId, j.Period })
            .HasDatabaseName("ix_journal_entries_company_period");
    }
}

